apiVersion: v1
kind: Service
metadata:
  name: dnscrypt-uk-tcp-service
  namespace: default
  labels:
    app: dnscrypt-uk
spec:
  ports:
    - protocol: TCP
      port: 443
  selector:
    app: dnscrypt-uk
  type: LoadBalancer
  loadBalancerIP: <YOUR IP HERE>
