apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnscrypt-uk-nfs-pvclaim
  labels:
    app: dnscrypt-uk-nfs
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
